name: Node.js CI
on:
  workflow_dispatch:

jobs:
  TEST:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v5.0.0
    
    - name: Use Node.js
      uses: actions/setup-node@v4.4
      with:
        node-version: '20.x'
        
          
    - name: Build the code
      run: npm ci
    - name: Build
      run: npm run build --if -present
    - name: Test
      run: npm test
