# This is a basic workflow to help you get started with Actions

name: Build Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build-Example:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: setup node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20  # or the version you need
          cache: npm # speeds up installs using lockfile

      - name: Install dependencies
        run: npm install

      - name: Create zip (app files + node_modules)
        run: |
          zip -r app-bundle.zip . \
            -x ".git/*" \
               ".github/*" \
               "node_modules/.cache/*" \
               "*.log" [web:36][web:40]
               
      - name: unittests npm
        run: npm test

      - name: Test Reporter
        uses: dorny/test-reporter@v2.1.1
        with:
            name: npm unit tests
        
